<?php

namespace Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function create($data){
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function delete($data){
        $this->_em->remove($data);
        $this->_em->flush();
    }

    public function update($data){
        $this->_em->persist($data);
        $this->_em->flush();
        return $this->_em;
    }

    public function users($enabled){
        $query = $this->createQueryBuilder('u')
                    ->where('u.enabled = :enabled')
                    ->setParameter('enabled', $enabled);

        return $query->getQuery()->getResult();
    }
}
